GET http://localhost:3000/api/posts

####
GET http://localhost:3000/api/posts/all-info

####

GET http://localhost:3000/api/categories

#### DELETE CATEGORY
DELETE http://localhost:3000/api/categories/6
####

GET http://localhost:3000/api/categories/count

#### Create new category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Birds"
}